services:
  krakend:
    image: krakend:2.9.4
    ports:
      - 8000:8000
    volumes:
      - ./configs/gateway/krakend.json:/etc/krakend/krakend.json
    networks:
      - dev_stafe
  grafana:
    image: grafana/grafana:10.2.3
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3003:3000
    volumes:
      - ./storage/grafana:/var/lib/grafana
    networks:
      - dev_stafe
  
  jaeger:
    image: jaegertracing/all-in-one:1.54
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "5778:5778" # serve configs
      - "16686:16686" # serve frontend UI
      - "4317:4317"   # otlp grpc: we remap this to be able to run other envs
      - "4318:4318" 
    networks:
      - dev_stafe
  
  
networks:
  dev_stafe:
    external: true
      
      