services:
  krakend:
    image: krakend:2.9.4
    ports:
      - 8000:8000

    environment:
      - FC_ENABLE=1
      - FC_OUT=/etc/krakend/config/out.json
      - FC_TEMPLATES=/etc/krakend/config/templates
      - FC_SETTINGS=/etc/krakend/config/settings
      - FC_PARTIALS=/etc/krakend/config/partials
      - FC_CONFIG=/etc/krakend/config/flexible_config.json
      - ENVIRONMENT=PROD

    command: ["run","-d", "-c","/etc/krakend/config/krakend.tmpl"]
    volumes:
      - ./krakend:/etc/krakend/config
    networks:
      - dev_stafe
networks:
  dev_stafe:
    external: true