services:
  krakend:
    image: krakend:2.9.4
    ports:
      - 8000:8000
    volumes:
      - ./configs/krakend.json:/etc/krakend/krakend.json
    networks:
      - dev_stafe
networks:
  dev_stafe:
    external: true
      
      