services:
  krakend:
    image: krakend:2.9.4
    ports:
      - 8000:8000

    environment:
      - FC_ENABLE=1
      - FC_OUT=/etc/krakend/config/out.json
      - FC_TEMPLATES=/etc/krakend/config/templates
      - FC_SETTINGS=/etc/krakend/config/settings
      - FC_PARTIALS=/etc/krakend/config/partials
      - FC_SETTINGS_DEBUG=1
      - FC_DEBUG=1
      - ENVIRONMENT=PROD

    entrypoint: ["sh", "/etc/krakend/config/entrypoint.sh"]
    volumes:
      - ./krakend:/etc/krakend/config
    networks:
      - dev_stafe
networks:
  dev_stafe:
    external: true