services:
  microservice01:
    image: node:22-alpine
    command: sh -c "cd /app && yarn install && yarn start:dev"
    volumes:
      - ./:/app 
    ports:
      - 3000:3000
    networks:
      - dev_stafe
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.20.0.7:12201"
        tag: "microservice01"

networks:
  dev_stafe:
    external: true
